### ISSUE TITLE
Redirect short URL for installer

### ISSUE THREAD

**Issue by crschardt** [PhotonVision/photon-image-modifier#27]
The short URL for the installer, https://git.io/JJrEP , points to `install.sh` in the photonvision repo. It should be redirected to the version of `install.sh` in this repo: https://raw.githubusercontent.com/PhotonVision/photon-image-modifier/master/install.sh

**Comment by crschardt** [comment]
So, [git.io](https://github.blog/changelog/2022-04-25-git-io-deprecation/) is deprecated, so there is no way to update the existing short URL. In addition, even though GitHub has agreed to keep existing short URLs working, that could always change in the future. Either, we don't move the install script, or we need to use a different URL shortener. Any preferences?

**Comment by mcm001** [comment]
We could edit that instal script to just curl the real install script from this repo?

**Comment by crschardt** [comment]
So, leave a simple `install.sh` in the main repo, but just have it run the one in this repo. I like that.  I want to test the updated script from EmDash00 on the images and then I'll put in the PRs to make these changes.

**Comment by mcm001** [comment]
Yeah exactly. Sounds like a plan!

**Comment by crschardt** [comment]
Closed by https://github.com/PhotonVision/photonvision/pull/1531
